### ISSUE TITLE
Worker not connecting to manager, with both discovery and hardcoded address.

### ISSUE THREAD

**Issue by mantissa-** [armadillica/flamenco-worker-python#5]
Manager: Linux Mint 18.1 with an active OpenVPN tunnel. (Python 3.5.2)
Worker: Xubuntu 16.04.3, also with OpenVPN active. (Python 3.5.2)

Flamenco worker is installed in a Python Virtual Environment as suggested.
Flamenco Manager is recognized and visible on the Blender Cloud.

Manager Output:

WARN[2017-08-17T14:04:35+02:00] WARNING: TLS not enabled!                    
2017/08/17 14:04:35 net.ListenPacket error: listen udp4 0.0.0.0:1900: bind: address already in use
ERRO[2017-08-17T14:04:35+02:00] Error creating ssdp server:  listen udp4 0.0.0.0:1900: bind: address already in use

Worker traceback when using discovery:

2017-08-17 13:55:41,247     INFO flamenco_worker.ssdp_discover Finding Flamenco Manager through UPnP/SSDP discovery.
Traceback (most recent call last):
  File "/home/mantissa/Applications/flamenco-worker/bin/flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "/home/mantissa/Applications/flamenco-worker/lib/python3.5/site-packages/flamenco_worker/cli.py", line 43, in main
    manager_url = ssdp_discover.find_flamenco_manager()
  File "/home/mantissa/Applications/flamenco-worker/lib/python3.5/site-packages/flamenco_worker/ssdp_discover.py", line 77, in find_flamenco_manager
    sock.sendto(DISCOVERY_MSG, (dest, 1900))
PermissionError: [Errno 1] Operation not permitted

Worker traceback when using hardcoded manager IP:

2017-08-17 14:00:56,382     INFO flamenco_worker.worker.FlamencoWorker Starting up
2017-08-17 14:00:56,382     INFO flamenco_worker.worker.FlamencoWorker Registering at manager
2017-08-17 14:00:56,383     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Connecting to database flamenco-worker.db
2017-08-17 14:00:56,386  WARNING flamenco_worker.worker.FlamencoWorker Unable to POST to manager /register-worker, retrying in 30 seconds: Invalid URL '/register-worker': No schema supplied. Perhaps you meant http:///register-worker?

**Comment by sybrenstuvel** [comment]
Hey Midge, thanks for reporting.

```
WARN[2017-08-17T14:04:35+02:00] WARNING: TLS not enabled!
```

This is expected when you don't use TLS certificates. If that's what you want, you can ignore it.

```
2017/08/17 14:04:35 net.ListenPacket error: listen udp4 0.0.0.0:1900: bind: address already in use
ERRO[2017-08-17T14:04:35+02:00] Error creating ssdp server: listen udp4 0.0.0.0:1900: bind: address already in use
```

Do you have any idea which other program is listening on that port? You can do `netstat -anlup | grep 1900` to find out.

```
File "/home/mantissa/Applications/flamenco-worker/lib/python3.5/site-packages/flamenco_worker/ssdp_discover.py", line 77, in find_flamenco_manager
sock.sendto(DISCOVERY_MSG, (dest, 1900))
PermissionError: [Errno 1] Operation not permitted
```

Can you retry for me, with the latest version of Flamenco-Worker from [git master](https://github.com/armadillica/flamenco-worker-python/archive/master.zip)? Before running, please change `flamenco-worker.cfg` so that it `level = DEBUG` in the `[logger_flamenco_worker]` section.

```
Worker traceback when using hardcoded manager IP:

2017-08-17 14:00:56,382 INFO flamenco_worker.worker.FlamencoWorker Starting up
2017-08-17 14:00:56,382 INFO flamenco_worker.worker.FlamencoWorker Registering at manager
2017-08-17 14:00:56,383 INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Connecting to database flamenco-worker.db
2017-08-17 14:00:56,386 WARNING flamenco_worker.worker.FlamencoWorker Unable to POST to manager /register-worker, retrying in 30 seconds: Invalid URL '/register-worker': No schema supplied. Perhaps you meant http:///register-worker?
```

Can you show me the `manager_url` setting in your worker config?

**Comment by mantissa-** [comment]
Finally had some time to do more testing, here's my results:

- **TLS**: Once I get everything up and running, I'll be enabling TLS, so we can ignore that for now.

- **Port 1900**: I found out that Emby Server was running on port 1900 / 1901 for DNLA purposes. Once shutdown, the error disappeared, so I'll have to figure out how to have them coexist.

- **Worker**: Updated from Git and still getting the same error, here's the DEBUG level trace:
```
2017-08-23 12:32:09,642    DEBUG flamenco_worker.cli Starting
2017-08-23 12:32:09,642     INFO flamenco_worker.ssdp_discover Finding Flamenco Manager through UPnP/SSDP discovery.
2017-08-23 12:32:09,643    DEBUG flamenco_worker.ssdp_discover Sending to AddressFamily.AF_INET 0.0.0.0
2017-08-23 12:32:10,644    DEBUG flamenco_worker.ssdp_discover Sending to AddressFamily.AF_INET6 ::
Traceback (most recent call last):
  File "/home/mantissa/Applications/flamenco-worker/bin/flamenco-worker", line 11, in <module>
    sys.exit(main())
  File "/home/mantissa/Applications/flamenco-worker/lib/python3.5/site-packages/flamenco_worker/cli.py", line 43, in main
    manager_url = ssdp_discover.find_flamenco_manager()
  File "/home/mantissa/Applications/flamenco-worker/lib/python3.5/site-packages/flamenco_worker/ssdp_discover.py", line 77, in find_flamenco_manager
    sock.sendto(DISCOVERY_MSG, (dest, 1900))
PermissionError: [Errno 1] Operation not permitted

```
Currently manager url is set to nothing for autodiscovery:

```
# The URL of the Flamenco Manager. Leave empty for auto-discovery via UPnP/SSDP.
manager_url = 
```
I'm new to running stuff in a Vritual Environment though, so it might be something I misconfigured?
To start the worker I run the following commands:

- source /path_to_worker/bin/activate
- (flamenco-worker) flamenco-worker

**Comment by sybrenstuvel** [comment]
- Port 1900: It would be great if they could co-exist. If you have any leads, please let me know.
- Worker: it seems that it only gets the permission error when sending to an IPv6 address. I could catch those errors and only stop the Worker if both IPv4 and IPv6 fail.
- The manager URL: you said it gave some error when using hardcoded manager IP, so I was wondering about the `manager_url` setting in that particular case.

**Comment by sybrenstuvel** [comment]
About the permission error: can you retry for me again with the latest version of Flamenco-Worker from [git master](https://github.com/armadillica/flamenco-worker-python/archive/master.zip)? It should now only fail if both IPv4 and IPv6 fail.

**Comment by mantissa-** [comment]
I had updated to the latest git version of the worker.
I got it to connect when hardcoding the internal network address, and figured out my mistake.

I had tried 10.0.0.123 and 10.0.0.123:8083 before without success.
Changing it to the full http address got it to connect: manager_url = http://10.0.0.123:8083/
It seems so obvious now that it works. :)

One question though, flamenco-worker keeps looking for the config file in my home directory, rather than the venv bin directory. Is there any way to specify it to look within the virtual environment?

**Comment by sybrenstuvel** [comment]
> Changing it to the full http address got it to connect

Great!

Does autodetection work for you as well, with the latest git master? And I mean latest latest, I just pushed a fix an hour ago.

> One question though, flamenco-worker keeps looking for the config file in my home directory, rather than the venv bin directory. Is there any way to specify it to look within the virtual environment?

It looks for the config file in the current directory, so if your current directory is `/home/mantissa/flamenco-stuff/worker` when you give the `flamenco-worker` command, it'll try and load `/home/mantissa/flamenco-stuff/worker/flamenco-worker.cfg`. You can also pass `--config /path/to/flamenco-worker.cfg` if you want.

It'll also always try to load `$HOME/.flamenco-worker.cfg`.

**Comment by mantissa-** [comment]
Alright, so I figured I would go for a fresh install from the Git clone to make sure the latest version is running as expected and now I'm having issues with the installation.

So I cloned the latest git version to my home directory and recreated the virtual environment from scratch. Upon installation it's erroring out as follows:

```
mantissa@Zuse:~$ python3 -m venv Applications/flamenco-worker/
mantissa@Zuse:~$ cd Applications/flamenco-worker/bin/
mantissa@Zuse:~/Applications/flamenco-worker/bin$ source activate
(flamenco-worker) mantissa@Zuse:~/Applications/flamenco-worker/bin$ python3 /home/mantissa/flamenco-worker-python/setup.py install
running install
running bdist_egg
running egg_info
creating flamenco_worker.egg-info
writing flamenco_worker.egg-info/PKG-INFO
writing dependency_links to flamenco_worker.egg-info/dependency_links.txt
writing entry points to flamenco_worker.egg-info/entry_points.txt
writing top-level names to flamenco_worker.egg-info/top_level.txt
writing requirements to flamenco_worker.egg-info/requires.txt
writing manifest file 'flamenco_worker.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'flamenco_worker.egg-info/SOURCES.txt'
writing manifest file 'flamenco_worker.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/flamenco_worker
error: can't copy 'README.md': doesn't exist or not a regular file
```

**Comment by sybrenstuvel** [comment]
You want to run `setup.py` from the source directory, not from the virtualenv's `bin` directory.

**Comment by mantissa-** [comment]
So I did that a few days ago, and then my server died.
Been rebuilding it since, but it might be a while before I'm able to revisit this, have a lot going on at the moment.

Once I get a chance though, I'll report back if it's still problematic.

**Comment by sybrenstuvel** [comment]
Then let's close this issue, as it seems that the original problem has been solved. Of course we welcome a new ticket if you run into any trouble!

**Comment by rickpalo** [comment]
I am having the same issue.
Manager and Worker both on the same machine, Ubuntu 18.04.  On initial installation of the worker (v 2.2.1), I get the 'Unable to POST to manager /sign-on' warning.  I changed the level to DEBUG.  I have tried both auto-detect and hard-coding the url.

2019-01-19 09:51:13,902    DEBUG flamenco_worker.cli Starting, pid=11412
2019-01-19 09:51:13,902     INFO flamenco_worker.cli Starting Flamenco Worker 2.2.1
2019-01-19 09:51:13,902     INFO flamenco_worker.ssdp_discover Finding Flamenco Manager through UPnP/SSDP discovery.
2019-01-19 09:51:13,905    DEBUG flamenco_worker.ssdp_discover Sending to AddressFamily.AF_INET, dest=239.255.255.250
2019-01-19 09:51:14,907     INFO flamenco_worker.cli Found Flamenco Manager at http://192.168.1.14:8083/
2019-01-19 09:51:14,908    DEBUG flamenco_worker.patch_asyncio Patching ue._UnixReadPipeTransport.resume_reading
2019-01-19 09:51:14,917     INFO flamenco_worker.worker.FlamencoWorker Starting up
2019-01-19 09:51:14,917     INFO flamenco_worker.worker.FlamencoWorker Signing on at manager.
2019-01-19 09:51:14,917    DEBUG flamenco_worker.upstream.FlamencoManager Creating new HTTP session
2019-01-19 09:51:14,918    DEBUG flamenco_worker.upstream.FlamencoManager POST http://192.168.1.14:8083/sign-on with JSON: {"supported_task_types": ["sleep", "blender-render", "file-management", "exr-...
2019-01-19 09:51:14,922    DEBUG flamenco_worker.upstream_update_queue.TaskUpdateQueue Inspecting queued task updates.
2019-01-19 09:51:14,922     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Connecting to database flamenco-worker.db
2019-01-19 09:51:15,027    DEBUG flamenco_worker.upstream_update_queue.TaskUpdateQueue Vacuuming database
2019-01-19 09:51:15,104  WARNING flamenco_worker.worker.FlamencoWorker Unable to POST to manager /sign-on, retrying in 30 seconds: 401 Client Error: Unauthorized for url: http://192.168.1.14:8083/sign-on
2019-01-19 09:51:45,106    DEBUG flamenco_worker.upstream.FlamencoManager POST http://192.168.1.14:8083/sign-on with JSON: {"supported_task_types": ["sleep", "blender-render", "file-management", "exr-...

**Comment by sybrenstuvel** [comment]
`401 Client Error: Unauthorized for url` indicates this is not the same error. The Worker connects just fine, but uses invalid credentials. This is a side-effect when you delete the Manager's database. Run the Worker with `flamenco-worker --reregister` to solve this.

**Comment by rickpalo** [comment]
Thank you!  That solved the problem.
