### ISSUE TITLE
Trouble in windows 10 with workers

### ISSUE THREAD

**Issue by insertcoindottv** [armadillica/flamenco-worker-python#7]
Hi all, we're trying to setup Flamenco, we already talk with Francesco Siddi that told us to write here our problem.

We got this error "PermissionError: [WinError 5] Access is denied" while trying to startup worker on differents machine.

In attach the configuration file for Manager and worker.
Any1 know how to get this done?
Thanks.
[flamenco-worker.log](https://github.com/armadillica/flamenco-worker-python/files/1715997/flamenco-worker.log)
[flamenco-manager.zip](https://github.com/armadillica/flamenco-worker-python/files/1715999/flamenco-manager.zip)

**Comment by sybrenstuvel** [comment]
There are a few things I notice in the `flamenco-manager.yaml` file. First of all, **IMMEDIATELY** re-link the manager to Blender Cloud or at least revoke its current access token. The file you attached here still has its secret token in there, which allows anybody to act on your Flamenco Manager's behalf on Blender Cloud. Don't share things that are called "secret", please.

The `blender` variable for Windows is configured as `'"C:\Program Files\Blender Foundation\Blender" --enable-new-depsgraph'`. Backslashes are discouraged, as they can act as escape characters depending on  the context they are in. Replace them with [forward slashes](https://www.flamenco.io/docs/user_manual/installation/#manager-configuration) and try again. If that works, good. If not, please try installing Blender in a directory without spaces in the name and try again.

Note that the test task configuration and `render` variable also contain backslashes, which should be fixed.

Furthermore, the test configuration uses the `{job_storage}` variable, which hasn't been defined. You'll want to define a path replacement variable with that name too, which will define where Flamenco writes its job files to.

**Comment by insertcoindottv** [comment]
Thanks Sybren, we will try asap.
Will let you know.
Max.

**Comment by insertcoindottv** [comment]
No way.. this is what i got:

PS P:\_iNSTALLERs_\_Blender\Flamenco\flamenco-worker-2.1.0-windows> .\flamenco-worker.exe -t -1
2018-02-12 15:04:53,942  WARNING flamenco_worker.cli Test mode enabled, overriding task_types='test-blender-render'
2018-02-12 15:04:53,945     INFO flamenco_worker.cli Running in single-task mode, will stop after performing one task.
2018-02-12 15:04:53,949     INFO flamenco_worker.worker.FlamencoWorker Starting up
2018-02-12 15:04:53,950     INFO flamenco_worker.worker.FlamencoWorker Signing on at manager.
2018-02-12 15:04:53,952     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Connecting to database flamenco-worker.db
2018-02-12 15:04:54,108     INFO flamenco_worker.worker.FlamencoWorker Manager accepted sign-on.
2018-02-12 15:04:54,133     INFO flamenco_worker.worker.FlamencoWorker Telling Manager we are in state 'testing'
2018-02-12 15:04:54,135     INFO flamenco_worker.worker.FlamencoWorker Entering main loop
2018-02-12 15:04:59,367     INFO flamenco_worker.worker.FlamencoWorker Received task: 5a819f09da133f4a6bcf418b
2018-02-12 15:04:59,367     INFO flamenco_worker.worker.FlamencoWorker Task changed status to active, pushing to manager
2018-02-12 15:04:59,368     INFO flamenco_worker.worker.FlamencoWorker Updating task 5a819f09da133f4a6bcf418b with status 'active' and activity Activity(activity='', current_command_idx=0, task_progress_percentage=0, command_progress_percentage=0)
2018-02-12 15:04:59,396    ERROR flamenco_worker.worker.FlamencoWorker Uncaught exception executing task 5a819f09da133f4a6bcf418b
Traceback (most recent call last):
  File "flamenco_worker\worker.py", line 399, in fetch_task
  File "asyncio\futures.py", line 381, in __iter__
  File "asyncio\tasks.py", line 310, in _wakeup
  File "asyncio\futures.py", line 294, in result
  File "asyncio\tasks.py", line 240, in _step
  File "flamenco_worker\runner.py", line 57, in execute
  File "flamenco_worker\commands.py", line 94, in run
  File "flamenco_worker\commands.py", line 525, in validate
  File "shlex.py", line 273, in split
  File "shlex.py", line 263, in __next__
  File "shlex.py", line 90, in get_token
  File "shlex.py", line 166, in read_token
ValueError: No closing quotation
2018-02-12 15:04:59,409     INFO flamenco_worker.worker.FlamencoWorker Task changed status to failed, pushing to manager
2018-02-12 15:04:59,409     INFO flamenco_worker.worker.FlamencoWorker Updating task 5a819f09da133f4a6bcf418b with status 'failed' and activity Activity(activity='Uncaught exception: ValueError No closing quotation', current_command_idx=0, task_progress_percentage=0, command_progress_percentage=0)
2018-02-12 15:04:59,410     INFO flamenco_worker.worker.FlamencoWorker Running in single-task mode, exiting.
2018-02-12 15:04:59,410     INFO flamenco_worker.worker.FlamencoWorker Shutting down by request of the Manager or due to single-task mode
2018-02-12 15:04:59,429  WARNING flamenco_worker.may_i_run.MayIRun Shutting down.
2018-02-12 15:04:59,431     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Pushing task update to Manager
2018-02-12 15:04:59,433  WARNING flamenco_worker.worker.FlamencoWorker Shutting down
2018-02-12 15:04:59,434  WARNING flamenco_worker.runner.TaskRunner abort_current_task: Aborting command BlenderRenderCommand(task_id='5a819f09da133f4a6bcf418b', command_idx=0, identifier='blender_render.(task_id=5a819f09da133f4a6bcf418b, command_idx=0)', _log=<logging.Logger object at 0x0000016C01DEF240>, readline_timeout=3600, proc=Attribute(name='proc', default=NOTHING, validator=<instance_of validator for type <class 'asyncio.subprocess.Process'>>, repr=True, cmp=True, hash=True, init=False, convert=None, metadata=mappingproxy({})))
2018-02-12 15:04:59,435     INFO flamenco_worker.commands.blender_render.(task_id=5a819f09da133f4a6bcf418b, command_idx=0) Aborting subprocess
2018-02-12 15:04:59,436     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue flush_and_report: trying one last push to get updates to Manager
2018-02-12 15:04:59,528     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Pushing task update to Manager
2018-02-12 15:04:59,623  WARNING flamenco_worker.upstream_update_queue.TaskUpdateQueue Stopping work loop
2018-02-12 15:04:59,625     INFO flamenco_worker.worker.FlamencoWorker shutdown(): signing off at Manager
2018-02-12 15:04:59,702     INFO flamenco_worker.cli Waiting to give tasks the time to stop gracefully
2018-02-12 15:05:00,703  WARNING flamenco_worker.cli Closing asyncio loop
2018-02-12 15:05:00,705  WARNING flamenco_worker.cli Flamenco Worker is shut down
PS P:\_iNSTALLERs_\_Blender\Flamenco\flamenco-worker-2.1.0-windows>

----------------------
Is possible to talk via Skype or something, so i can show you my monitor...?
Thanks in advance.

**Comment by insertcoindottv** [comment]
![12-02-15 10](https://user-images.githubusercontent.com/36404492/36100579-02ab9a98-1007-11e8-9907-82d3d8e54817.jpg)

**Comment by fsiddi** [comment]
Hi @insertcoindottv – there is no need to attach screenshots. Attaching the log and formatting it properly is usually enough (check out the formatting tools available).

**Comment by insertcoindottv** [comment]
Thanks Francesco ! :D

**Comment by sybrenstuvel** [comment]
`ValueError: No closing quotation` indicates that there is probably still a quoting issue. Please share your new `flamenco-manager.yaml` file.

**Comment by insertcoindottv** [comment]
[flamenco-manager - Copia.zip](https://github.com/armadillica/flamenco-worker-python/files/1716872/flamenco-manager.-.Copia.zip)

**Comment by sybrenstuvel** [comment]
I have replaced the attachment with just the contents of the file, formatted properly between triple backticks. Simply being able to read instead of having to download a file and unpacking it makes life easier for us.

And indeed, there is a quoting error in the `blender` variable value for the `windows` platform.

There are also still backslashes...

**Comment by insertcoindottv** [comment]
Can you correct the error please? or just give to me an example so i can better understand how to do it right without Backslash?
Thanks.

**Comment by sybrenstuvel** [comment]
> Can you correct the error please?

First of all, properly quote your strings. Change this:

`    windows: C:/Program Files/Blender Foundation/blender/blender.exe" --enable-new-depsgraph`

into this:

`    windows: "C:/Program Files/Blender Foundation/blender/blender.exe" --enable-new-depsgraph`

And change backslashes to regular slashes:

```
    job_storage: p:\temp\progetto
    render_output: p:\temp\render
```

into this:

```
    job_storage: p:/temp/progetto
    render_output: p:/temp/render
```

**Comment by insertcoindottv** [comment]
ok i did it but nothing change.
This is Manager:

```
PS P:\_iNSTALLERs_\_Blender\Flamenco\flamenco-manager-2.1.0-windows> .\flamenco-manager.exe
[36mINFO[0m[2018-02-12T17:19:43+01:00] Starting Flamenco Manager                     [36mversion[0m=2.1.0
[31mFATA[0m[2018-02-12T17:19:44+01:00] Unable to load configuration                  [31merror[0m="unmarshal: yaml: line 22: did not find expected key"
PS P:\_iNSTALLERs_\_Blender\Flamenco\flamenco-manager-2.1.0-windows> INFO[2018-02-12T17:19:46+01:00] Getting tasks from upstream Flamenco https://cloud.blender.org/api/flamenco/managers/5a73241982a2024ffce4c431/depsgraph
INFO[2018-02-12T17:20:04+01:00] ImageWatcherHTTPPush: Channel started at /imagewatch for 192.168.0.2:63117
INFO[2018-02-12T17:20:07+01:00] ImageWatcherHTTPPush: Channel started at /imagewatch for 192.168.0.2:63120
INFO[2018-02-12T17:20:14+01:00] Worker signed on                              remote_addr="192.168.0.2:63128" worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
WARN[2018-02-12T17:20:14+01:00] WorkerAckStatusChange: acknowledged status is not the same as requested status. Accepting anyway.  ack_status=testing previous_status=starting remote_addr="192.168.0.2:63128" status_requested= worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:14+01:00] Getting tasks from upstream Flamenco https://cloud.blender.org/api/flamenco/managers/5a73241982a2024ffce4c431/depsgraph
INFO[2018-02-12T17:20:18+01:00] created test blender render task              job_storage="p:\\temp\\progetto\\max-pc-5a732cdf836eabfb645f1fde" local_blendfile="static\\testfiles\\test.blend" render_output="p:\\temp\\render\\max-pc-5a732cdf836eabfb645f1fde" task_blendfile="p:\\temp\\progetto\\max-pc-5a732cdf836eabfb645f1fde\\test.blend" worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:18+01:00] queued test tasks for worker                  queued_task_types="[test-blender-render]" unknown_task_types="[]" worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:18+01:00] workerAction: action OK                       action=send-test-job remote_addr="192.168.0.2:63133" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:19+01:00] ScheduleTask: assigning task to worker        remote_addr="192.168.0.2:63129" task_id=5a81bec2da133f4a6bcf86af worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:19+01:00] ScheduleTask: assigned task to worker         remote_addr="192.168.0.2:63129" task_id=5a81bec2da133f4a6bcf86af worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:19+01:00] QueueTaskUpdateFromWorker: Received task update  remote_addr="192.168.0.2:63129" task_id=5a81bec2da133f4a6bcf86af task_status=active worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:19+01:00] QueueTaskUpdateFromWorker: Received task update  remote_addr="192.168.0.2:63129" task_id=5a81bec2da133f4a6bcf86af task_status=failed worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
WARN[2018-02-12T17:20:20+01:00] Worker signing off                            remote_addr="192.168.0.2:63129" worker="192.168.0.2 (Max-PC)" worker_id=5a732cdf836eabfb645f1fde
INFO[2018-02-12T17:20:43+01:00] Removed 0 stale tasks.
INFO[2018-02-12T17:24:46+01:00] Getting tasks from upstream Flamenco https://cloud.blender.org/api/flamenco/managers/5a73241982a2024ffce4c431/depsgraph
INFO[2018-02-12T17:29:46+01:00] Getting tasks from upstream Flamenco https://cloud.blender.org/api/flamenco/managers/5a73241982a2024ffce4c431/depsgraph
INFO[2018-02-12T17:30:44+01:00] Removed 0 stale tasks.
INFO[2018-02-12T17:34:46+01:00] Getting tasks from upstream Flamenco https://cloud.blender.org/api/flamenco/managers/5a73241982a2024ffce4c431/depsgraph
```

And this is worker:

```
PS P:\_iNSTALLERs_\_Blender\Flamenco\flamenco-worker-2.1.0-windows> .\flamenco-worker.exe -t -1
2018-02-12 17:20:14,451  WARNING flamenco_worker.cli Test mode enabled, overriding task_types='test-blender-render'
2018-02-12 17:20:14,454     INFO flamenco_worker.cli Running in single-task mode, will stop after performing one task.
2018-02-12 17:20:14,458     INFO flamenco_worker.worker.FlamencoWorker Starting up
2018-02-12 17:20:14,459     INFO flamenco_worker.worker.FlamencoWorker Signing on at manager.
2018-02-12 17:20:14,460     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Connecting to database flamenco-worker.db
2018-02-12 17:20:14,554     INFO flamenco_worker.worker.FlamencoWorker Manager accepted sign-on.
2018-02-12 17:20:14,556     INFO flamenco_worker.worker.FlamencoWorker Telling Manager we are in state 'testing'
2018-02-12 17:20:14,558     INFO flamenco_worker.worker.FlamencoWorker Entering main loop
2018-02-12 17:20:19,758     INFO flamenco_worker.worker.FlamencoWorker Received task: 5a81bec2da133f4a6bcf86af
2018-02-12 17:20:19,759     INFO flamenco_worker.worker.FlamencoWorker Task changed status to active, pushing to manager
2018-02-12 17:20:19,759     INFO flamenco_worker.worker.FlamencoWorker Updating task 5a81bec2da133f4a6bcf86af with status 'active' and activity Activity(activity='', current_command_idx=0, task_progress_percentage=0, command_progress_percentage=0)
2018-02-12 17:20:19,786    ERROR flamenco_worker.worker.FlamencoWorker Uncaught exception executing task 5a81bec2da133f4a6bcf86af
Traceback (most recent call last):
  File "flamenco_worker\worker.py", line 399, in fetch_task
  File "asyncio\futures.py", line 381, in __iter__
  File "asyncio\tasks.py", line 310, in _wakeup
  File "asyncio\futures.py", line 294, in result
  File "asyncio\tasks.py", line 240, in _step
  File "flamenco_worker\runner.py", line 57, in execute
  File "flamenco_worker\commands.py", line 94, in run
  File "flamenco_worker\commands.py", line 525, in validate
  File "shlex.py", line 273, in split
  File "shlex.py", line 263, in __next__
  File "shlex.py", line 90, in get_token
  File "shlex.py", line 166, in read_token
ValueError: No closing quotation
2018-02-12 17:20:19,797     INFO flamenco_worker.worker.FlamencoWorker Task changed status to failed, pushing to manager
2018-02-12 17:20:19,798     INFO flamenco_worker.worker.FlamencoWorker Updating task 5a81bec2da133f4a6bcf86af with status 'failed' and activity Activity(activity='Uncaught exception: ValueError No closing quotation', current_command_idx=0, task_progress_percentage=0, command_progress_percentage=0)
2018-02-12 17:20:19,798     INFO flamenco_worker.worker.FlamencoWorker Running in single-task mode, exiting.
2018-02-12 17:20:19,799     INFO flamenco_worker.worker.FlamencoWorker Shutting down by request of the Manager or due to single-task mode
2018-02-12 17:20:19,818  WARNING flamenco_worker.may_i_run.MayIRun Shutting down.
2018-02-12 17:20:19,820     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Pushing task update to Manager
2018-02-12 17:20:19,822  WARNING flamenco_worker.worker.FlamencoWorker Shutting down
2018-02-12 17:20:19,823  WARNING flamenco_worker.runner.TaskRunner abort_current_task: Aborting command BlenderRenderCommand(task_id='5a81bec2da133f4a6bcf86af', command_idx=0, identifier='blender_render.(task_id=5a81bec2da133f4a6bcf86af, command_idx=0)', _log=<logging.Logger object at 0x000001C37AE0E358>, readline_timeout=3600, proc=Attribute(name='proc', default=NOTHING, validator=<instance_of validator for type <class 'asyncio.subprocess.Process'>>, repr=True, cmp=True, hash=True, init=False, convert=None, metadata=mappingproxy({})))
2018-02-12 17:20:19,825     INFO flamenco_worker.commands.blender_render.(task_id=5a81bec2da133f4a6bcf86af, command_idx=0) Aborting subprocess
2018-02-12 17:20:19,826     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue flush_and_report: trying one last push to get updates to Manager
2018-02-12 17:20:19,913     INFO flamenco_worker.upstream_update_queue.TaskUpdateQueue Pushing task update to Manager
2018-02-12 17:20:20,011  WARNING flamenco_worker.upstream_update_queue.TaskUpdateQueue Stopping work loop
2018-02-12 17:20:20,012     INFO flamenco_worker.worker.FlamencoWorker shutdown(): signing off at Manager
2018-02-12 17:20:20,089     INFO flamenco_worker.cli Waiting to give tasks the time to stop gracefully
2018-02-12 17:20:21,090  WARNING flamenco_worker.cli Closing asyncio loop
2018-02-12 17:20:21,092  WARNING flamenco_worker.cli Flamenco Worker is shut down
PS P:\_iNSTALLERs_\_Blender\Flamenco\flamenco-worker-2.1.0-windows>
```

**Comment by insertcoindottv** [comment]
And this is the actual YAML:

```
# Configuration file for Flamenco Manager.
# For an explanation of the fields, refer to flamenco-manager-example.yaml
#
# NOTE: this file will be overwritten by Flamenco Manager's web-based configuration system.
#
# This file was written on 2018-02-12 15:04:32 +01:00

database_url: ""
database_path: ./db
listen: :8083
own_url: http://192.168.0.2:8083/
flamenco: https://cloud.blender.org/
manager_id: 5a73241982a2024ffce4c431
manager_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
tlskey: ""
tlscert: ""
download_task_sleep: 5m0s
download_task_recheck_throttle: 10s
variables:
  blender:
    darwin: /Volume/Applications/Blender/blender
    linux: /linux/path/to/blender
    windows: "C:/Program Files/Blender Foundation/blender/blender.exe" --enable-new-depsgraph
path_replacement:
  render:
    darwin: /render
    linux: /render
    windows: P:/temp
task_update_push_max_interval: 30s
task_update_push_max_count: 50
cancel_task_fetch_max_interval: 30s
active_task_timeout_interval: 3m0s
active_worker_timeout_interval: 15m0s
task_cleanup_max_age: 336h0m0s
watch_for_latest_image: ""
ssdp_discovery: false
ssdp_device_uuid: 7401c189-ef69-434b-b4d8-56d00075faf5
test_tasks:
  test_blender_render:
    job_storage: p:/temp/progetto
    render_output: p:/temp/render

```

**Comment by sybrenstuvel** [comment]
There is a fatal error reading your configuration file:

`FATA 2018-02-12T17:19:44+01:00] Unable to load configuration error="unmarshal: yaml: line 22: did not find expected key"`

**Comment by insertcoindottv** [comment]
Yeess.... ehm.. ... so?  What is this? 
Opening YAML with an editor, the line 22 is:

linux: /linux/path/to/blender

Any tips... ?
Thank you.

**Comment by sybrenstuvel** [comment]
> Yeess.... ehm.. ... so? What is this?

I don't understand your question.

Often parse errors can be caused by a malformed file just above or below the indicated line of error. The offending line is:

`windows: "C:/Program Files/Blender Foundation/blender/blender.exe" --enable-new-depsgraph`

I'm not sure why the single quotes were removed. When changing it to this it works fine:

`windows: '"C:/Program Files/Blender Foundation/blender/blender.exe" --enable-new-depsgraph'`

**Comment by insertcoindottv** [comment]
Yeeeesssss Yesssssss

It finally worked !!! omg we're so happy !!
Thanks a lot guys.
Have a nice life.

Max.
